MovieDB/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kisah', include('kisah.urls')),
    path('',include('movies.urls')),
    path('browse/', include('browse.urls')),
    path('horrorgraphy/', include('hgraphy.urls')),
    path('analyst', include('analyst.urls')),
]


   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browse/urls.py
from django.urls import path
from . import views

app_name = 'app_browse'

urlpatterns = [
    path("", views.PageMovies.as_view(), name='browse'),
    path("statistic", views.Statistic.as_view(), name='statistic')
]

hgraphy/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


app_name='app_hgraphy'
urlpatterns = [
    path("",views.ActorView.as_view(),name='hgraphy'),
    path("api/search-person/", views.person_suggestion, name="person_suggestion"),

]

kisah/urls.py
from django.urls import path
from . import views

app_name = 'app_kisah'

urlpatterns = [
    path("", views.index, name='kisah')
]

movies/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


app_name='app_movies'
urlpatterns = [
    path("",views.index,name='movies'),
    path("movie/<int:movie_id>/", views.detail_movie, name="detail_movie"),
    path('search-api/', views.search_api, name='search_api')


]

templates/snippets/content.html
<div class="content">
  <div class="upcoming">
    <h4>&#x1F39E; Upcoming Horror Movies</h4>
    <div class="movie-list">
      {% for m in upcoming_movies %}
      <a href="/movie/{{m.id}}/" class="movie-link">
        <div class="poster-wrapper">
          <img src="https://image.tmdb.org/t/p/w500{{ m.poster_path }}" alt="{{ m.title }}" width="150" />
          <h6 class="poster_name">{{ m.title }}</h6>
          <h6>Release: {{ m.release_date }}</h6>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
  <div class="top-movie">
    <h4>&#x1F3A5; Best 2025 Horror Movie</h4>
    <div class="movie-list">
      {% for m in top_movies %}
      <a href="/movie/{{m.id}}/" class="movie-link">
        <div class="poster-wrapper">
          <img src="https://image.tmdb.org/t/p/w500{{ m.poster_path }}" alt="{{ m.title }}" width="150" />
          <span class="rating">⭐ {{ m.vote_average|floatformat:1 }}</span>
          <h6 class="title poster_name">{{ m.title }}</h6>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</div>

templates/snippets/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary custom-navbar" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{% static 'img/logo_mdb.png' %}" alt="logo" />
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <!-- Menu kiri -->
      <div class="navbar-nav ms-auto me-5">
        <a class="nav-link active" href="{% url 'app_movies:movies' %}">🏠︎Home</a>
        <a class="nav-link" href="{% url 'app_browse:browse' %}">🔎Browse</a>
        <a class="nav-link" href="{% url 'app_hgraphy:hgraphy' %}">💀Horrorgraphy</a>
        <a class="nav-link" href="{% url 'app_browse:statistic' %}">📊Analyst</a>
      </div>

      <!-- Search bar kanan -->
      <div class="nav-search" style="position: relative">
        <input id="movieSearchInput" type="search" placeholder="🔍Search movies..." aria-label="Search movies" autocomplete="off" />
        <div id="searchResults" role="listbox" aria-labelledby="movieSearchInput" class="search-dropdown" hidden></div>
      </div>
    </div>
  </div>
</nav>